<?php
namespace service\sys;
use core\db\Mysql;
use core\Model;
use core\App;
use lib\TreeUtils;

/***
 * 角色 路由逻辑
 * Class RoleService
 * @package service\
 */
class  RoleService  extends Model{

    public $table='zw_admin_group';
    public function __construct()
    {
        parent::__construct(App::$db_ecstore);
    }

    public  $error;

    public function  lists(Array $fields = array(), $page = 1, $pageSize = 50)
    {
        return parent::lists($fields, $page, $pageSize); // TODO: Change the autogenerated stub
    }

    public function  getActionTree()
    {
        $sql ="select id,scopes_name as name,parent_id ,scopes_value from  zw_admin_scopes";
        $actions = $this->db->transform($sql,'id');

        $tree = TreeUtils::list2tree($actions);
        return $tree;
    }

    public function  addAction($data)
    {
       $id=  $this->db->insert($data ,'zw_admin_scopes' );
       return $id;
    }

    public function updateAction($data)
    {
       $where = "id=".$data['id'];
       return $this->db->update($data ,$where,'zw_admin_scopes');
    }

}