<?php
namespace service\dal;
use core\App;
use core\db\Mysql;
use core\Model;
class OrderModel extends Model{
    public $table='zw_orders';
    public $fields = ['order_id' ,'total_amount','pay_status', 'order_status'  ,'ship_status', 'reship_status' ,'client_examine' ,'financial_examine' ,'order_channel'];

    public function __construct()
    {
        parent::__construct(new  Mysql(App::$config['ecstore']));
    }


    public function lists(Array $fields = array(), $page = 1, $pageSize = 10)
    {
        return parent::lists($fields , $page, $pageSize); // TODO: Change the autogenerated stub
    }
    /** 获取订单的状态 */
    public function getOrdersStatus( $orderIds)
    {
        if(is_array($orderIds))
            $where = " where order_id in (".implode(',',$orderIds).")";
        else
            $where = " where order_id=".$orderIds;
        $sql_orders  = "SELECT order_id,order_status,ship_status,reship_status,client_examine,financial_examine FROM zw_orders ".$where;
        //$rows=  $this->db->queryAll($sql_orders);
        $rows = $this->db->transform($sql_orders,'order_id');
        return $rows;
    }

    /***
     * 更新发货状态
     * @param $orderids
     * @param int $status
     * @return bool|\mysqli_result
     */
    public function  updateShipStatus($orderids ,$status=2 )
    {
        $pickingTime = time();
        if(is_array($orderids))
        {
            $where = " where  order_id in (".implode(',',$orderids).")";
        }else{
            $where = " where  order_id=".$orderids;
        }
        $sql ="UPDATE zw_orders SET ship_status='{$status}',print_status_1=print_status_1+1,picking_time='$pickingTime',update_time='$pickingTime'".$where;
       return $this->execute($sql);
    }

    /**
     * 扫描物流单号提取订单信息
     *@param string $deliveryNumber
     *@return array
     */
    public function getOderInfoByDeliveryNumber($deliveryNumber)
    {
        if(empty($deliveryNumber))
        {
            return false;
        }

        $sql = "SELECT * FROM zw_orders WHERE delivery_number='$deliveryNumber' AND order_status='active' LIMIT 1";
        $order = $this->db->queryFirstRow($sql);

        if($order)
        {
            $order['sku_total'] = 0;
            $sql = "SELECT * FROM zw_order_sku WHERE order_id='{$order['order_id']}'";
            $rows = $this->db->queryAllRows($sql);
            if($rows)
            {
                foreach($rows as $key=>$val)
                {
                    $sql = "SELECT barcode FROM zw_products WHERE sku='{$val['sku']}'";
                    $product = $this->db->queryFirstRow($sql);
                    if($product)
                    {
                        $rows[$key]['barcode'] = $product['barcode'];
                        $order['sku_total'] += $val['quantity'];
                    }
                }
                $order['sku_list'] = $rows;
            }
            else
            {
                $order['sku_list'] = array();
            }
        }

        return $order;
    }




}